/** JavaScript is a general-purpose scripting language that conforms to the ECMAScript specification. 
* The ECMAScript specification is a blueprint for creating a scripting language. 
* JavaScript is an implementation of that blueprint. On the whole, 
* JavaScript implements the ECMAScript specification.
* The language we usually call "JavaScript" is formally known as "EcmaScript". 
* The new version of JavaScript, known as "ES6",
* offers a number of new features that extend the power of the language
*/